### ISSUE TITLE
The result of the LTI plugin is not propagated to the course

### ISSUE THREAD

**Issue by rdekoster** [ilifau/ExternalContent#7]
The result of the LTI plugin - which in itself is correctly received - is not propagated to the parent Course for Ilias 6.x. This is true for LTI plugin versions 1.6.2 and 1.6.3.
I have set the **Course's Learning Progress option Status is Determined by a Collection of Items** and enabled the Course's Learning Path option **Determines Learning Progress**.

Like mentioned above, the LTI result is received but whatever the outcome, the Course status remains busy.
I tested this on Ilias 6.4 and 6.7.

**Comment by fneumann** [comment]
Now I found the bug and solved it in the master-ilias53 branch. Please pull the latest changes and try it again.
